#!/bin/bash

# Load environment variables
source ./scripts/load-config

# Prepare the database
bundle exec rails db:create db:migrate db:seed

# Remove old PID if exists
rm -f tmp/pids/server.pid

# Start server on the correct port
exec bundle exec rails server -b 0.0.0.0 -p ${PORT:-8080}
